### ISSUE TITLE
Multi-scale Volumetric Occlusion Causes Banding When Close to an Object.

### ISSUE THREAD

**Issue by ballisticfox** [shadowmage45/TUFX#31]
**Bug**
Replication is simple, just enable Ambient Occlusion and zoom into your craft, you've probably seen this before since it's enabled on the default configs.

This could be do to KSP's limitations with Shader Models >3 unless properly set-up or maybe something different entirely. From a brief discussion with Linx this may be due to Unity using the forward rendering path causing Screen-Space effects to apply incorrectly.
If I remember correctly this effect was working in pre-1.9 ksp but I cannot confirm this right now (I'll check in a bit).

I believe it's something to do with the _thickness modifier_ as playing with that has yielded interesting results.

If a fix for this is not found I highly suggest removing AO from the default configs or swapping them to the alternate mode

**Comment by JonnyOThan** [comment]
It's mentioned here: https://github.com/shadowmage45/TUFX/issues/14 but I don't mind tracking it as a separate issue since I'd really like to find a solution.

SSAO usually works by detecting a sudden difference in the depth values in the scene; it seems likely that the unified camera that was introduced in 1.9 has such a crazy depth range that it produces artifacts.  However we never see z-fighting at the same ranges so there must be something more complicated going on.
